### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by masterhacka** [Pretronic/PretronicLibraries#36]
Hi there,

![F7CF3D1A-88C7-47A1-A9F9-11476E94F063](https://user-images.githubusercontent.com/9753608/153297906-55c38d1a-5872-4e2d-89da-a5f708089796.png)

https://github.com/Pretronic/PretronicLibraries/blob/86faf72f2b571224122b6cbadcefdd4b3b898148/pretroniclibraries-logging/src/main/java/net/pretronic/libraries/logging/bridge/slf4j/SLF4JBridgeServiceProvider.java#L69

**Comment by masterhacka** [comment]
No help?

**Comment by Fridious** [comment]
@masterhacka Hey, sorry for the late response. 

Currently we are not working much on this library. 

Does the problem occurs anymore or could you solve it?

**Comment by RomualdLewandoski** [comment]
Welcome from 2023 still have the issue could you do something ? 

```log
java.lang.ExceptionInInitializerError: null
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:299) ~[?:?]
        at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:272) ~[?:?]
        at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1782) ~[?:?]
        at something.bot.Bot.<init>(Bot.java:25) ~[?:?]
        at something.SOMETHING.onEnable(SOMETHING.java:105) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:287) ~[bungeecord.jar:git:Aegis-Bootstrap:1.20-R0.1-SNAPSHOT:95137c8:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:322) ~[bungeecord.jar:git:Aegis-Bootstrap:1.20-R0.1-SNAPSHOT:95137c8:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:41) ~[bungeecord.jar:git:Aegis-Bootstrap:1.20-R0.1-SNAPSHOT:95137c8:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:27) ~[bungeecord.jar:git:Aegis-Bootstrap:1.20-R0.1-SNAPSHOT:95137c8:unknown]
Caused by: java.lang.UnsupportedOperationException
        at net.pretronic.libraries.logging.bridge.slf4j.SLF4JBridgeServiceProvider.getMDCAdapter(SLF4JBridgeServiceProvider.java:69) ~[bungeecord1.jar:git:Aegis-Bootstrap:1.20-R0.1-SNAPSHOT:95137c8:unknown]
        at org.slf4j.MDC.<clinit>(MDC.java:93) ~[bungeecord.jar:git:Aegis-Bootstrap:1.20-R0.1-SNAPSHOT:95137c8:unknown]
        ```
